# Generated by Django 4.2.30 on 2026-04-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('card_no', models.CharField(max_length=30, unique=True, verbose_name='借书证号')),
                ('id_card', models.CharField(blank=True, max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('status', models.CharField(choices=[('active', '正常'), ('suspended', '挂起')], default='active', max_length=20, verbose_name='状态')),
                ('max_borrow', models.IntegerField(default=5, verbose_name='最大借阅数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '读者',
                'verbose_name_plural': '读者',
            },
        ),
    ]
