# Generated by Django 4.2.30 on 2026-04-11 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_reader_user'),
        ('books', '0001_initial'),
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='申请日期')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('reject_reason', models.CharField(blank=True, max_length=200, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='申请图书')),
                ('borrow_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrow.borrowrecord', verbose_name='借阅记录')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.reader', verbose_name='读者')),
            ],
            options={
                'verbose_name': '借书申请',
                'verbose_name_plural': '借书申请',
            },
        ),
    ]
