# Generated by Django 4.2.30 on 2026-04-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='条形码')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='馆藏位置')),
                ('status', models.CharField(choices=[('available', '可借'), ('borrowed', '已借出'), ('damaged', '损坏'), ('lost', '丢失')], default='available', max_length=20, verbose_name='状态')),
                ('cataloged_at', models.DateTimeField(auto_now_add=True, verbose_name='编目时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '图书副本',
                'verbose_name_plural': '图书副本',
            },
        ),
    ]
