# Generated by Django 4.2.30 on 2026-04-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, verbose_name='书名')),
                ('quantity', models.IntegerField(default=1, verbose_name='采购数量')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='供应商')),
                ('order_date', models.DateField(verbose_name='采购日期')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='预计到货日期')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('ordered', '已订购'), ('received', '已入库'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '采购记录',
                'verbose_name_plural': '采购记录',
            },
        ),
    ]
